# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zibostan
tagline:          'Bernard Blog'
description:      "Bernard's personal blog"
url:              https://blog.bernardwong.com

author:
  name:           'Bernard Wong'
  url:            https://twitter.com/mdo

paginate:         5

plugins: [jekyll-paginate]

github:
  repo:           https://github.com/bernardzzz